blank_issues_enabled: true
contact_links:
  - name: 'Send an e-mail to the maintainers'
    url: 'https://services.acm.org/public/vcard/vcard.cfm?handle=andrei.petrov'
    about: Please do NOT use this email to post issues or feature requests (only important notifications).