style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - chore
        - docs
  commit_groups:
    title_maps:
      feat: Features
      fix: Fixes
      perf: Performance Improvements
      refactor: Refactoring
      chore: Chores
      docs: Documentation
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE