---
name: tag-and-docker-build-and-push

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.REPO_MANAGEMENT_TOKEN }}
  REGISTRY_URL: 'quay.io'
  FULL_DOCKER_REGISTRY_NAME: 'quay.io/andov_go/helm-packager'

jobs:
  containerized-application:
    runs-on: ubuntu-latest
    outputs:
      tag: steps.bump-version-and-push-tag.outputs.new_tag
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: '0'
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            application:
              - added|modified: 'Dockerfile'
              - added|modified: 'src/**'
      - name: Bump version and push tag
        if: steps.changes.outputs.application == 'true'
        id: bump-version-and-push-tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: Set up QEMU
        if: steps.changes.outputs.application == 'true'
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        if: steps.changes.outputs.application == 'true'
        uses: docker/setup-buildx-action@v2
      - name: Login to ${{ env.REGISTRY_URL }} Container Registry
        if: steps.changes.outputs.application == 'true'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.QUAY_IO_CI_PUSH_AND_PULL_USERNAME }}
          password: ${{ secrets.QUAY_IO_CI_PUSH_AND_PULL_PASSWORD }}
      - name: Build and push the image
        if: steps.changes.outputs.application == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.FULL_DOCKER_REGISTRY_NAME }}:${{ steps.bump-version-and-push-tag.outputs.new_tag }},${{ env.FULL_DOCKER_REGISTRY_NAME }}:latest